### ISSUE TITLE
미리보기에 학회 로고 추가

### ISSUE THREAD

**Issue by malkoG** [HI-ARC/hi-arc.github.io#14]
<img width="644" alt="2019-02-12 10 18 54" src="https://user-images.githubusercontent.com/2427963/52638106-86448680-2f14-11e9-919d-9436d6299dbc.png">

미리보기에 나타나는 이미지가 좀 허전한데, 학회 로고가 들어가는게 좋을 것 같아요.

**Comment by KimHwon** [comment]
#16 에서 반영했습니다.
